import json
import os
import subprocess
from datetime import datetime
from pathlib import Path

import toml

from toolbelt.bootstrap.helm_env import render_helm_yaml
from toolbelt.git.branches import get_default_branch
from toolbelt.git.workflow import update_repo


def git_setup(
    target_path: Path,
    git_projects_workdir: Path,
    service_name: str | None = None,
    index_serena: bool = True,
) -> None:
    os.chdir(target_path)
    # Create .gitignored symlink to technical documentation directory
    techdocs_source = git_projects_workdir / "tech-docs" / f"{target_path.name}"
    techdocs_target = target_path / ".techdocs"
    if techdocs_source.exists() and not techdocs_target.exists():
        os.symlink(techdocs_source, techdocs_target)
    # Create .gitignored file for setup script. Ran for worktrees setup.
    setup_script = target_path / ".setup.sh"
    if not setup_script.exists():
        setup_script.write_text("#!/usr/bin/env sh\n")
        setup_script.chmod(0o755)
    if not (target_path / ".git-branches.toml").exists():
        git_branches_path = git_projects_workdir / "dotfiles/config/.git-branches.toml"
        git_branches = toml.loads(git_branches_path.read_text())
        default_branch = get_default_branch()
        git_branches["branches"]["main"] = default_branch
        (target_path / ".git-branches.toml").write_text(toml.dumps(git_branches))
    env_vars = render_helm_yaml(
        target_path,
        git_projects_workdir,
        service_name,
    )
    if (target_path / ".env").exists():
        original_dot_env = (target_path / ".env").read_text() if env_vars else ""
    else:
        (target_path / ".env").touch()
        original_dot_env = ""
    if env_vars:
        original_env_var_lines = [
            line.strip() for line in original_dot_env.split("\n") if line.strip()
        ]
        env_var_lines = [
            f"{k}={v}"
            for k, v in env_vars.items()
            if f"{k}={v}" not in original_env_var_lines
        ]
        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        updated_dot_env = (
            f"# ~~~ Start of env vars generated by toolbelt on {generated_at} ~~~\n"
            + "\n".join(env_var_lines)
            + f"\n# ~~~ End of env vars generated by toolbelt on {generated_at} ~~~\n"
            + original_dot_env
        )
        (target_path / ".env").write_text(updated_dot_env)
    if not (target_path / ".envrc").exists():
        (target_path / ".envrc").touch()
    if "dotenv" not in (target_path / ".envrc").read_text():
        with open(target_path / ".envrc", "a") as f:
            f.write("dotenv\n")
    if (target_path / ".pre-commit-config.yaml").exists():
        subprocess.run(["pre-commit", "install"], check=True)
    (target_path / ".cursor/rules").mkdir(parents=True, exist_ok=True)
    for file in (git_projects_workdir / "dotfiles/cursor/rules").glob("*.mdc"):
        target_file = target_path / ".cursor/rules" / file.name
        if not target_file.exists():
            os.symlink(file, target_file)
    if not (target_path / ".serena/project.yml").exists():
        subprocess.run(
            [
                "uvx",
                "--from",
                "git+https://github.com/oraios/serena",
                "serena",
                "project",
                "create",
            ],
            check=True,
            cwd=target_path,
        )
    cursor_mcp_relative_path = Path(".cursor/mcp.json")
    cursor_mcp_project_path = target_path / cursor_mcp_relative_path
    if not cursor_mcp_project_path.exists():
        cursor_mcp_project_path.write_text(
            json.dumps(
                {
                    "mcpServers": {
                        "serena": {
                            "command": "uvx",
                            "args": [
                                "--from",
                                "git+https://github.com/oraios/serena",
                                "serena",
                                "start-mcp-server",
                                "--context",
                                "ide-assistant",
                                "--enable-web-dashboard",
                                "false",
                                "--project",
                                str(target_path.absolute()),
                            ],
                        },
                    },
                },
                indent=4,
            )
        )
        git_info_exclude = target_path / ".git/info/exclude"
        if not git_info_exclude.exists():
            git_info_exclude.touch()
        if str(cursor_mcp_relative_path) not in git_info_exclude.read_text():
            with open(git_info_exclude, "a") as f:
                f.write(str(cursor_mcp_relative_path) + "\n")
    if index_serena:
        subprocess.run(
            [
                "uvx",
                "--from",
                "git+https://github.com/oraios/serena",
                "serena",
                "project",
                "index",
            ],
            check=True,
            cwd=target_path,
        )
    update_repo(target_path)
